apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
        - name: rest-service
          image: rest-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
